language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile
before_install:
  - gem install bundler
before_script:
  - cp config/settings.yml.sample config/settings.yml
script: "(rake db:migrate RAILS_ENV=test) && (bundle exec rake spec)"
notifications:
  email: false
