language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile
before_install:
  - gem install bundler -v 1.4.0.pre.2 --pre
bundler_args: '--jobs=4 --without deployment production development'
before_script:
  - cp config/settings.yml.sample config/settings.yml
script: "(rake db:migrate RAILS_ENV=test) && (bundle exec rspec spec)"
notifications:
  email: false
